### ISSUE TITLE
Bug: SQLite does not support `FixedSizeList` data type

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#2227]
**Describe the bug**

Embeddings create a `FixedSizeList` array that contains the contents of the vectorization from the embedding. When trying to accelerate these results with SQLite, the runtime fails:

```bash
2024-08-07T05:38:57.659964Z  INFO runtime: Initialized results cache; max size: 128.00 MiB, item ttl: 1s
thread '<unnamed>' panicked at /home/william/.cargo/git/checkouts/datafusion-table-providers-4cff62bc40e10a80/d7e7f22/src/sql/arrow_sql_gen/statement.rs:812:14:
not implemented: Data type mapping not implemented for FixedSizeList(Field { name: "item", data_type: Float32, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, 384)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-08-07T05:38:57.747459Z  WARN runtime: Unable to attach data connector postgres: Unable to create dataset acceleration: Acceleration creation failed: Unable to create table: External error: Unable to create table in Sqlite: ConnectionClosed
thread '<unnamed>' panicked at /home/william/.cargo/git/checkouts/datafusion-table-providers-4cff62bc40e10a80/d7e7f22/src/sql/arrow_sql_gen/statement.rs:812:14:
not implemented: Data type mapping not implemented for FixedSizeList(Field { name: "item", data_type: Float32, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, 384)
thread '<unnamed>' panicked at /home/william/.cargo/git/checkouts/datafusion-table-providers-4cff62bc40e10a80/d7e7f22/src/sql/arrow_sql_gen/statement.rs:812:14:
not implemented: Data type mapping not implemented for FixedSizeList(Field { name: "item", data_type: Float32, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, 384)
^C2024-08-07T05:39:01.574499Z  INFO runtime: Goodbye!
```

**To Reproduce**

1. Create a spicepod with an embedding on a dataset
2. Use SQLite acceleration
3. See error

**Expected behavior**

The embedding and dataset should accelerate successfully, as it does with `arrow` acceleration.

**Spicepod**
```yaml
version: v1beta1
kind: Spicepod
name: spiceai
datasets:
- from: postgres:customer
  name: customer
  mode: read
  acceleration:
    engine: sqlite
    refresh_sql: "SELECT * FROM customer LIMIT 10"
  embeddings:
    - column: c_name
      use: text_embedder
  params:
    pg_host: localhost
    pg_port: 5432
    pg_db: tpch
    pg_user: mydb_user
    pg_pass: secret
    pg_sslmode: disable

embeddings:
  - from: huggingface:huggingface.co/sentence-transformers/all-MiniLM-L6-v2
    name: text_embedder
    params:
      max_length: "128"
```

**Output of the `describe table`**
```
| c_name_embedding | FixedSizeList(Field { name: "item", data_type: Float32, nullable: false, dict_id: 0, dict_is_ordered: false, metadata: {} }, 384) | YES         |
```

**spice, spiced, OS info**
- spice version: `v0.17.1-beta-rc.8924cc7d`
- spiced version: `v0.17.1-beta-rc.8924cc7d`
- OS info: `Linux pop-os 6.9.3-76060903-generic #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J x86_64 x86_64 x86_64 GNU/Linux`

**Have you tried this on the latest `trunk` branch?**

Yes

**Comment by Sevenannn** [comment]
- Fixed-size mapping from arrow -> row is implemented through: https://github.com/spiceai/spiceai/issues/2252
- Closed as the Sqlite array supported is tracked in: https://github.com/spiceai/spiceai/issues/1867
