### ISSUE TITLE
Unsupported column type Date (Postgres dataconnector)

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#908]
**Describe the bug**

I see the following error when using Postgres as data source and table from [TCP-H benchmark](https://www.tpc.org/tpch/)  

2024-03-23T22:04:54.845164Z  INFO runtime::opentelemetry: Spice Runtime OpenTelemetry listening on 127.0.0.1:50052
thread 'tokio-runtime-worker' panicked at crates/arrow_sql_gen/src/postgres.rs:355:14:
**not implemented: Unsupported column type Date**
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Spice should NOT crash. There should be user friendly warning instead**

**To Reproduce**

1. Create Postgres table using schema below

```
CREATE TABLE public.orders (
	o_orderkey int4 NOT NULL,
	o_custkey int4 NOT NULL,
	o_orderstatus bpchar(1) NOT NULL,
	o_totalprice numeric(15, 2) NOT NULL,
	o_orderdate date NOT NULL,
	o_orderpriority bpchar(15) NOT NULL,
	o_clerk bpchar(15) NOT NULL,
	o_shippriority int4 NOT NULL,
	o_comment varchar(79) NOT NULL
);
```
2.  Add created Postgres table above as data source to your spicepod ([instructions](https://docs.spiceai.org/connectors/postgres/))  
3. Run Spice
5. See error

thread 'tokio-runtime-worker' panicked at crates/arrow_sql_gen/src/postgres.rs:355:14:
**not implemented: Unsupported column type Date**
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Screenshots**
![image](https://github.com/spiceai/spiceai/assets/981580/21de683f-e2e3-488c-8a2a-89341715af1f)

**Additional context**
orders table above is part of [TCP-H benchmark](https://www.tpc.org/tpch/)

**Comment by sgrebnov** [comment]
Fixed by https://github.com/spiceai/spiceai/pull/911
